FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o zipweather-gateway ./cmd/main.go

FROM debian:bullseye-slim

WORKDIR /app

COPY --from=builder /app/zipweather-gateway .

EXPOSE 8080

ENTRYPOINT ["./zipweather-gateway"]