FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o loadtester ./cmd/main.go

# Final minimal image
FROM debian:bullseye-slim

WORKDIR /app

COPY --from=builder /app/loadtester .

# Default entrypoint
ENTRYPOINT ["./loadtester"]